#!/bin/bash

DBNAME=fias
DB_USERNAME=fias
DB_USER_PASSWORD=fias

if [ $1 != '' ]; then
	cd $1
fi

ACTST=`ls AS_ACTSTAT*`
CENTERST=`ls AS_CENTERST*`
CURENTST=`ls AS_CURENTST*`
ESTST=`ls AS_ESTSTAT*`
OPERST=`ls AS_OPERSTAT*`
SOCRBASE=`ls AS_SOCRBASE*`
STRST=`ls AS_STRSTAT*`
ADDROBJ=`ls AS_ADDROBJ*`

QUERYSTR="BEGIN;
LOAD XML LOCAL INFILE '$ACTST' REPLACE INTO TABLE actstat  ROWS IDENTIFIED BY '<ActualStatus>';
LOAD XML LOCAL INFILE '$CENTERST' REPLACE INTO TABLE centerst ROWS IDENTIFIED BY '<CenterStatus>';
LOAD XML LOCAL INFILE '$CURENTST' REPLACE INTO TABLE curentst ROWS IDENTIFIED BY '<CurrentStatus>';
LOAD XML LOCAL INFILE '$ESTST'    REPLACE INTO TABLE eststat  ROWS IDENTIFIED BY '<EstateStatus>';
LOAD XML LOCAL INFILE '$OPERST'   REPLACE INTO TABLE operstat ROWS IDENTIFIED BY '<OperationStatus>';
LOAD XML LOCAL INFILE '$SOCRBASE' REPLACE INTO TABLE socrbase ROWS IDENTIFIED BY '<AddressObjectType>';
LOAD XML LOCAL INFILE '$STRST'    REPLACE INTO TABLE strstat  ROWS IDENTIFIED BY '<StructureStatuses>';
LOAD XML LOCAL INFILE '$ADDROBJ'  REPLACE INTO TABLE addrobj  ROWS IDENTIFIED BY '<Object>';
COMMIT;"

echo $QUERYSTR
echo

echo Importing XML data...

mysql -B -u$DB_USERNAME -p$DB_USER_PASSWORD -e "$QUERYSTR" $DBNAME

if [ $? == 0 ]; then
	echo Done
fi
